services:
  mcstats:
    build: /docker/faultieroase-minecraft-stats/stats-api
    container_name: mcstats_api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /srv/minecraft/data/world/stats:/mcstats:ro
      - /srv/minecraft/data/usercache.json:/usercache.json:ro
    networks:
      - shared_minecraft_net

networks:
  shared_minecraft_net:
    external: true